services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - klokr-data:/root/.local/share/klokr
    networks:
      - klokr-net
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development  # Changed to Development
      - BackendUrl=http://backend:8080
    depends_on:
      - backend
    networks:
      - klokr-net
    restart: unless-stopped

networks:
  klokr-net:
    driver: bridge

volumes:
  klokr-data: